### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST

POST http://localhost:8080/aop/v1
Content-Type: text/plain


{"test" : "String"}
